### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by badukaire** [rg3/dhondt#2]
The script crashed with a encoding-related exception when processing a file with some latin1 encoding. I was running it on a ubuntu. Let me know if you are interested on the details and the file. The file was generated copy-pasting a result table from a website.

**Comment by badukaire** [comment]
I leave a comment here regarding my forked repo. I have added some features, basically plain text table output + command-line options. The main code remains untouched, I have tried to keep indenting to ease merging. I plan to refactor it with a class before I add more stuff.

I have no intention to use the code with commercial purposes, but let me know if you have any expectations regarding the use.

**Comment by rg3** [comment]
Dealing with encodings can be frustrating both in code and in external files. This tiny script is written with UTF-8 in mind, which is the common configuration for most Linux systems nowadays. The HTML output is declared to be in UTF-8 and the input file should be in UTF-8 too. I've tested that and it works for me. Feel free to reopen the issue if something fails using UTF-8.

By the way, to convert a Latin1 file to UTF-8 simply use `iconv -f LATIN1 -t UTF-8 -o OUTPUT_FILE INPUT_FILE` and be done with it.

**Comment by rg3** [comment]
Sorry, my mistake. The HTML output encoding is taken from the locale preferred encoding. As long as the input file encoding and locale configuration match, the script should work. Problems may arise with environments in one preferred locale and input in a different one.
